import { RECORD_TYPES, JSON_SCHEMAS, type RecordType } from './schemas'
import { EXAMPLES, EXAMPLE_NOTES } from './examples'

/**
 * Renders the field reference the agent team builds against, straight from the
 * emitted JSON Schema. Generated rather than written so the document cannot
 * drift from what the dashboard actually validates.
 *
 * See docs/specs/agent-data-contract.md (AC-7).
 */

export const FIELDS_START = '<!-- FIELDS:START — generated by pnpm schema:emit, do not edit -->'
export const FIELDS_END = '<!-- FIELDS:END -->'
export const EXAMPLES_START =
  '<!-- EXAMPLES:START — generated by pnpm schema:emit, do not edit -->'
export const EXAMPLES_END = '<!-- EXAMPLES:END -->'

interface Field {
  name: string
  type: string
  nullable: boolean
  enumValues: string[]
  required: boolean
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

/** A union member's branches, or the node itself when it is not a union. */
function branchesOf(schema: Record<string, unknown>): Record<string, unknown>[] {
  const anyOf = schema.anyOf
  if (Array.isArray(anyOf)) return anyOf.filter(isObject)
  return [schema]
}

function describeType(node: Record<string, unknown>): { type: string; nullable: boolean } {
  const anyOf = node.anyOf
  if (Array.isArray(anyOf)) {
    const parts = anyOf.filter(isObject)
    const nullable = parts.some((p) => p.type === 'null')
    const rest = parts.filter((p) => p.type !== 'null')
    const inner = rest.map((p) => describeType(p).type)
    return { type: inner.join(' | ') || 'null', nullable }
  }
  if (node.const !== undefined) return { type: `\`${String(node.const)}\``, nullable: false }
  if (node.type === 'array') {
    const items = isObject(node.items) ? describeType(node.items).type : 'unknown'
    return { type: `${items}[]`, nullable: false }
  }
  if (node.type === 'object') return { type: 'object', nullable: false }
  const format = typeof node.format === 'string' ? ` (${node.format})` : ''
  return { type: `${String(node.type ?? 'unknown')}${format}`, nullable: false }
}

function enumOf(node: Record<string, unknown>): string[] {
  if (Array.isArray(node.enum)) return node.enum.map(String)
  if (node.const !== undefined) return [String(node.const)]
  const anyOf = node.anyOf
  if (Array.isArray(anyOf)) {
    const values = anyOf.filter(isObject).flatMap(enumOf)
    return values.length === anyOf.filter(isObject).length ? values : []
  }
  return []
}

function fieldsOf(schema: Record<string, unknown>): Field[] {
  const byName = new Map<string, Field>()
  for (const branch of branchesOf(schema)) {
    const props = isObject(branch.properties) ? branch.properties : {}
    const required = new Set(Array.isArray(branch.required) ? branch.required.map(String) : [])
    for (const [name, raw] of Object.entries(props)) {
      if (!isObject(raw)) continue
      const { type, nullable } = describeType(raw)
      const existing = byName.get(name)
      const enumValues = enumOf(raw)
      if (!existing) {
        byName.set(name, { name, type, nullable, enumValues, required: required.has(name) })
        continue
      }
      // Present in more than one union branch: keep the widest description.
      if (existing.type !== type) existing.type = `${existing.type} | ${type}`
      existing.nullable = existing.nullable || nullable
      existing.enumValues = [...new Set([...existing.enumValues, ...enumValues])]
      existing.required = existing.required && required.has(name)
    }
  }
  return [...byName.values()]
}

/** Markdown tables are pipe-delimited, so any pipe inside a cell must be escaped. */
function cell(text: string): string {
  return text.replaceAll('|', '\\|')
}

/** A field whose values are all literals is an enum; its type is the primitive underneath. */
function primitiveOf(type: string): string {
  const first = type.split(' | ')[0] ?? type
  if (/^`-?\d+(\.\d+)?`$/.test(first)) return 'integer'
  if (first.startsWith('`')) return 'string'
  return first
}

function renderOne(type: RecordType): string {
  const rows = fieldsOf(JSON_SCHEMAS[type]).map((f) => {
    const values = f.enumValues.length ? f.enumValues.map((v) => `\`${v}\``).join(', ') : '—'
    const shown = f.enumValues.length ? primitiveOf(f.type) : f.type
    return `| \`${f.name}\` | ${cell(shown)} | ${f.required ? 'yes' : 'no'} | ${f.nullable ? 'yes' : 'no'} | ${cell(values)} |`
  })
  return [
    `### \`${type}\``,
    '',
    '| Field | Type | Required | Nullable | Allowed values |',
    '|---|---|---|---|---|',
    ...rows,
  ].join('\n')
}

export function renderFieldTables(): string {
  return RECORD_TYPES.map(renderOne).join('\n\n')
}

/** The worked examples printed in the handover document, each with its note. */
export function renderExamples(): string {
  return RECORD_TYPES.map((type) =>
    [
      `### \`${type}\``,
      '',
      EXAMPLE_NOTES[type],
      '',
      '```json',
      JSON.stringify(EXAMPLES[type], null, 2),
      '```',
    ].join('\n'),
  ).join('\n\n')
}
